# permissions for end users to view maps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: map-viewer-role
rules:
- apiGroups:
  - forward.techsquad.rocks
  resources:
  - maps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - forward.techsquad.rocks
  resources:
  - maps/status
  verbs:
  - get
