---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - forward.techsquad.rocks
  resources:
  - maps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - forward.techsquad.rocks
  resources:
  - maps/finalizers
  verbs:
  - update
- apiGroups:
  - forward.techsquad.rocks
  resources:
  - maps/status
  verbs:
  - get
  - patch
  - update
